name: Continuous Deployment

on:
  workflow_call:
      inputs:
        target:
          required: false
          type: string

jobs:
  checkout-branch:
    runs-on: ubuntu-latest
    steps:
      
    - uses: actions/checkout@v4     
      with: 
        ref: ${{ inputs.target || 'refs/heads/main' }}
        
    - name: Variables
      run: |
        echo "GITHUB_REF: $GITHUB_REF"

