name: Continuous Deployment

on:
  workflow_call:

jobs:
  display-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Variables
        run: |
          echo "GITHUB_REF: $GITHUB_REF"

