name: Continuous Deployment

on:
  workflow_call:
    inputs:
      target:
        required: false
        type: string
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  checkout-branch:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4     
      with: 
        ref: ${{ inputs.target || github.ref }}

    - run: |
        git status
        
    - name: Variables
      run: |
        echo "GITHUB_REF: $GITHUB_REF"
        echo "input.target: ${{ inputs.target }}"
        echo "GITHUB_REF=${{inputs.target}}" >> $GITHUB_REF
        echo "GITHUB_REF: $GITHUB_REF"
    
    - run: |
        echo "hello, you're in a different branch"
    
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"

    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"

    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"

    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
      
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"

